[profile.default]
src = "contracts"
include_paths = ["smtchecker-contracts"]
out = "build"
libs = ["lib"]
test = "test"
solc = "0.8.3"
force = true
optimizer = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
