
name: "Olympix Integration"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: pthakur-circle/integrate-repo/.github/workflows/olympix.yml@main
    secrets:
      OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
  